version: '3'
services:
  weblate:
    image: weblate/weblate
    privileged: true
    ports:
      - 8085:80
    volumes:
      - ./weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
  database:
    image: postgres:9.6-alpine
    privileged: true
    env_file:
      - ./environment
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
  apache:
    image: httpd
    privileged: true
    labels:
      - convox.port.443.protocol=tls
    ports:
      - 80:80
      - 443:80
    volumes:
      - ./apachecerts:/etc/ssl/certs
      - ./apacheconfig:/tmp
  cache:
    image: redis:4-alpine
    privileged: true
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis-data:/data
