version: '3'
services:
  weblate:
    image: weblate/weblate:4.2.2-3
    privileged: true
    ports:
      - 8088:8080
    volumes:
      - ./weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
  database:
    image: postgres:9.6-alpine
    privileged: true
    ports:
      - 5431:5432
    env_file:
      - ./environment
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:4-alpine
    privileged: true
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis-data:/data
