from httpd
COPY httpd.conf /usr/local/apache2/conf/httpd.conf
COPY httpd-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf
COPY httpd-ssl.conf /usr/local/apache2/conf/extra/httpd-ssl.conf 
RUN mkdir /usr/local/apache2/weblate
